### ISSUE TITLE
第二节 客户端调用服务后创建货运不成功

### ISSUE THREAD

**Issue by Fengly0503** [wuYin/shippy#10]
![1](https://user-images.githubusercontent.com/7435119/54503224-39b3f700-4969-11e9-8faf-7d7e95db3a0f.jpg)
![2](https://user-images.githubusercontent.com/7435119/54503240-47697c80-4969-11e9-81d0-97c77ad91487.jpg)
请教一下，服务端正常运行，客户端运行发现服务没有问题，但是返回的运行结果是 created:false 可能是什么原因导致，还有go-micro微服务调试，有什么好的实践建议吗？

**Comment by ycg000344** [comment]
遇到相同的问题了，请问解决了吗？



![image](https://user-images.githubusercontent.com/36219142/57831419-aae81d00-77e7-11e9-9d39-feb205a9cb90.png)

![image](https://user-images.githubusercontent.com/36219142/57831502-e682e700-77e7-11e9-8fc9-3d056e8512e7.png)

**Comment by ycg000344** [comment]
老哥，我解决了。

修改的地方：

![image](https://user-images.githubusercontent.com/36219142/57838587-8e53e100-77f7-11e9-861f-c4f2bcea41a8.png)

效果：

server:

![image](https://user-images.githubusercontent.com/36219142/57838619-a166b100-77f7-11e9-9644-bda9ad177e20.png)

client:

![image](https://user-images.githubusercontent.com/36219142/57838634-ab88af80-77f7-11e9-892a-6230ddc9e01f.png)
