### ISSUE TITLE
Docker run时报错：standard_init_linux.go:190: exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by Pingze-github** [wuYin/shippy#9]
查询发现是编辑结果的平台不正确，在Debian上改用`FROM debian:latest`后正常。

**Comment by Pingze-github** [comment]
仅在user-service中出现此问题

**Comment by ycg000344** [comment]
同样遇到这个问题，使用`alpine`无法执行二进制文件。

解决：
在`Makefile`中使用
```
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v .
```

参考这个 [链接](https://stackoverflow.com/questions/36279253/go-compiled-binary-wont-run-in-an-alpine-docker-container-on-ubuntu-host)
